/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    YourContract2: {
      abi: [
        {
          type: "impl",
          name: "MyFirstContract",
          interface_name: "contracts::YourContract2::IMyFirstContract",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::YourContract2::IMyFirstContract",
          items: [
            {
              type: "function",
              name: "get_value",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_value",
              inputs: [
                {
                  name: "cAddress",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "eventName",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "eventTitle",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "chain",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_Owner",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_cAddress",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_eventName",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_eventTitle",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_chain",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::YourContract2::YourContract2::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
  },
  sepolia: {
    YourContract2: {
      address:
        "0x076185ac9c6a56923d211618b4417f0ac7019f1d149bd40b0738c8f6b6dbd575",
      abi: [
        {
          type: "impl",
          name: "MyFirstContract",
          interface_name: "contracts::YourContract2::IMyFirstContract",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::YourContract2::IMyFirstContract",
          items: [
            {
              type: "function",
              name: "get_value",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_value",
              inputs: [
                {
                  name: "cAddress",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "eventName",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "eventTitle",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "chain",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_Owner",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_cAddress",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_eventName",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_eventTitle",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_chain",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::YourContract2::YourContract2::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
  },
} as const;

export default deployedContracts;
